CREATE TABLE `est_db`.`ADDRESS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LATITUDE` DOUBLE NOT NULL,
  `LONGITUDE` DOUBLE NOT NULL,
  `STREET_ADDRESS` VARCHAR(100) NOT NULL,
  `CITY` VARCHAR(100) NOT NULL,
  `STATE` VARCHAR(100) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `POSTAL_CODE` VARCHAR(45) NULL,
  `NOTES` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`));

