CREATE TABLE `est_db`.`PARKING_LOT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ACTIVE` TINYINT NOT NULL,
  `LOT_NUMBER` INT NOT NULL DEFAULT 1,
  `DESCRIPTION` VARCHAR(200) NULL,
  `SINCE` DATETIME NOT NULL,
  `ADDRESS` INT NOT NULL,
  `USER` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PARKING_LOT_1_idx` (`ADDRESS` ASC) VISIBLE,
  INDEX `fk_PARKING_LOT_USER_idx` (`USER` ASC) VISIBLE,
  CONSTRAINT `fk_PARKING_LOT_ADDRESS`
    FOREIGN KEY (`ADDRESS`)
    REFERENCES `est_db`.`ADDRESS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARKING_LOT_USER`
    FOREIGN KEY (`USER`)
    REFERENCES `est_db`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

