CREATE TABLE `est_db`.`RESERVATION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DRIVER` INT NOT NULL,
  `LENDER` INT NOT NULL,
  `VEHICLE` INT NOT NULL,
  `PARKING_LOT` INT NOT NULL,
  `DATE_FROM` DATETIME NOT NULL,
  `DATE_TO` DATETIME NOT NULL,
  `VALUE` DECIMAL(8,2) NOT NULL,
  `STATUS` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  INDEX `fk_RESERVATION_DRIVER_idx` (`DRIVER` ASC) VISIBLE,
  INDEX `fk_RESERVATION_LENDER_idx` (`LENDER` ASC) VISIBLE,
  INDEX `fk_RESERVATION_VEHICLE_idx` (`VEHICLE` ASC) VISIBLE,
  INDEX `fk_RESERVATION_PARKLOT_idx` (`PARKING_LOT` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVATION_DRIVER`
    FOREIGN KEY (`DRIVER`)
    REFERENCES `est_db`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVATION_LENDER`
    FOREIGN KEY (`LENDER`)
    REFERENCES `est_db`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVATION_VEHICLE`
    FOREIGN KEY (`VEHICLE`)
    REFERENCES `est_db`.`VEHICLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVATION_PARKLOT`
    FOREIGN KEY (`PARKING_LOT`)
    REFERENCES `est_db`.`PARKING_LOT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

