CREATE TABLE `est_db`.`REVIEW` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `RESERVATION` INT NOT NULL,
  `DATE_REVIEWED` DATETIME NOT NULL,
  `SCORE` INT NOT NULL,
  `COMMENT` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_REVIEW_RESERV_idx` (`RESERVATION` ASC) VISIBLE,
  CONSTRAINT `fk_REVIEW_RESERV`
    FOREIGN KEY (`RESERVATION`)
    REFERENCES `est_db`.`RESERVATION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

