CREATE TABLE `est_db`.`SCHEDULES` (
  `PARKING_LOT` INT NOT NULL,
  `MONDAY` TINYINT NULL DEFAULT 0,
  `TUESDAY` TINYINT NULL DEFAULT 0,
  `WEDNESDAY` TINYINT NULL DEFAULT 0,
  `THURSDAY` TINYINT NULL DEFAULT 0,
  `FRIDAY` TINYINT NULL DEFAULT 0,
  `SATURDAY` TINYINT NULL DEFAULT 0,
  `SUNDAY` TINYINT NULL DEFAULT 0,
  `FROM_HOUR` TINYINT NULL,
  `TO_HOUR` TINYINT NULL,
  INDEX `FK_SCH_PL_idx` (`PARKING_LOT` ASC) VISIBLE,
  CONSTRAINT `FK_SCH_PL`
    FOREIGN KEY (`PARKING_LOT`)
    REFERENCES `est_db`.`PARKING_LOT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

