
CREATE TABLE `est_db`.`VEHICLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PLATE` VARCHAR(45) NOT NULL,
  `ACTIVE` TINYINT NOT NULL,
  `USER` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `PLATE_UNIQUE` (`PLATE` ASC) VISIBLE,
  INDEX `fk_VEHICLE_USER_idx` (`USER` ASC) VISIBLE,
  CONSTRAINT `fk_VEHICLE_USER`
    FOREIGN KEY (`USER`)
    REFERENCES `est_db`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

